FROM mcr.microsoft.com/dotnet/sdk:7.0.403-jammy-amd64 AS build
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

# Copy the remaining source code and build the application.
COPY . ./
RUN dotnet publish -c Release -o out -r linux-arm64 --self-contained=false

# Build the runtime image.
FROM mcr.microsoft.com/dotnet/runtime:7.0-jammy-arm64v8 AS runtime
WORKDIR /app
COPY --from=build /app/out ./


# Start the application.
ENTRYPOINT ["dotnet", "MailZort.dll"]
